use crate::gemini::{models, parse_live_event, GeminiClient, GeminiEvent, GeminiLiveClient};
use crate::gemini::GeminiStream;
use base64::{engine::general_purpose::STANDARD, Engine as _};
use futures::{SinkExt, StreamExt};
use serde::Serialize;
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::sync::mpsc;
use tracing::{info, warn};
use tokio_tungstenite::tungstenite::Message;

/// Final tags generated by Gemini Live
#[derive(Debug, Clone, Serialize)]
pub struct LiveTags {
    pub tags: Vec<String>,
}

pub enum GeminiStreamMessage {
    Audio(Vec<u8>),
    TurnComplete,
}

pub struct GeminiLiveStreamer {
    pub audio_tx: mpsc::UnboundedSender<GeminiStreamMessage>,
    pub stream_epoch_ms: u64,
}

impl GeminiLiveStreamer {
    pub async fn connect(
        tags_tx: mpsc::UnboundedSender<LiveTags>,
        system_instruction: &str,
    ) -> Result<Self, String> {
        info!("🎙️ Connecting to Gemini Live Streamer...");

        let tags_tool = GeminiLiveClient::define_tool(
            "submit_tags",
            "Submit delivery tags. Call this whenever the user pauses or finishes a thought.",
            serde_json::json!({
                "type": "OBJECT",
                "properties": {
                    "tags": {
                        "type": "ARRAY",
                        "items": {"type": "STRING"}
                    }
                }
            })
        );

        // Connect to Gemini Live
        let client: GeminiLiveClient = match GeminiClient::builder()
            .model(models::FLASH_LIVE)
            .system_instruction(system_instruction)
            .response_modalities(vec!["AUDIO".to_string()]) // The model requires AUDIO modality.
            .tools(vec![tags_tool])
            .build_live()
        {
            Ok(c) => c,
            Err(e) => return Err(format!("Failed to build Gemini Live client: {}", e)),
        };

        let ws_stream: GeminiStream = match client.connect().await {
            Ok(stream) => stream,
            Err(e) => return Err(format!("Failed to connect to Gemini Live: {}", e)),
        };

        let stream_epoch_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_millis() as u64;

        let (mut ws_write, mut ws_read) = ws_stream.split();
        let (audio_tx, mut audio_rx) = mpsc::unbounded_channel::<GeminiStreamMessage>();

        // Writer Task: Read PCM bytes from frontend, wrap in RealtimeInput JSON, send to Gemini
        tokio::spawn(async move {
            while let Some(msg) = audio_rx.recv().await {
                match msg {
                    GeminiStreamMessage::Audio(pcm_data) => {
                        let base64_audio = STANDARD.encode(&pcm_data);
                        
                        let realtime_input = serde_json::json!({
                            "realtimeInput": {
                                "audio": {
                                    "mimeType": "audio/pcm;rate=16000",
                                    "data": base64_audio
                                }
                            }
                        });

                        if let Err(e) = ws_write.send(Message::Text(realtime_input.to_string().into())).await {
                            warn!("Gemini Live write error: {}", e);
                            break;
                        }
                    }
                    GeminiStreamMessage::TurnComplete => {
                        let turn_msg = serde_json::json!({
                            "clientContent": {
                                "turnComplete": true
                            }
                        });
                        info!("🚀 Forcing Gemini Turn Complete!");
                        if let Err(e) = ws_write.send(Message::Text(turn_msg.to_string().into())).await {
                            warn!("Gemini Live write error: {}", e);
                            break;
                        }
                    }
                }
            }
            info!("🔇 Gemini Live writer closed");
        });

        // Reader Task: Read text events from Gemini Live and parse tags
        tokio::spawn(async move {
            let mut last_tags: Vec<String> = vec![];
            let mut last_tags_time = tokio::time::Instant::now();

            while let Some(msg) = ws_read.next().await {
                let text_opt = match msg {
                    Ok(Message::Text(text)) => Some(text.to_string()),
                    Ok(Message::Binary(bin)) => Some(String::from_utf8_lossy(&bin).to_string()),
                    Ok(Message::Close(cf)) => {
                        tracing::warn!("Gemini Live closed connection: {:?}", cf);
                        break;
                    }
                    Err(e) => {
                        warn!("Gemini Live WebSocket error: {}", e);
                        break;
                    }
                    _ => None,
                };

                if let Some(text_str) = text_opt {
                    if let Some(event) = parse_live_event(&text_str) {
                        match event {
                            GeminiEvent::Text(t) => {
                                let cleaned = t.trim().trim_start_matches("```json").trim_start_matches("```").trim_end_matches("```").trim();
                                if let Ok(tags) = serde_json::from_str::<Vec<String>>(cleaned) {
                                    let now = tokio::time::Instant::now();
                                    if tags == last_tags && now.duration_since(last_tags_time).as_secs() < 3 {
                                        // Ignore exact duplicate tags emitted by race conditions between VAD and TurnComplete
                                        tracing::debug!("🏷️ [Gemini Live] Ignored duplicate tags (within 3s)");
                                    } else {
                                        tracing::info!("🏷️ [Gemini Live] Generated Tags: {:?}", tags);
                                        last_tags = tags.clone();
                                        last_tags_time = now;
                                        let _ = tags_tx.send(LiveTags { tags });
                                    }
                                } else {
                                    tracing::warn!("🏷️ [Gemini Live] Raw Text (Not JSON): {}", t);
                                    let _ = tags_tx.send(LiveTags { tags: vec![t.clone()] });
                                }
                            }
                            _ => {}
                        }
                    }
                }
            }
            info!("🔌 Gemini Live reader disconnected");
        });

        Ok(Self {
            audio_tx,
            stream_epoch_ms,
        })
    }
}
